mem_site/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path(r'admin/', admin.site.urls),
    url(r'^accounts/password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_new.html')),
    url(r'^accounts/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done_new.html')),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,24})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm_new.html')),
    url(r'^accounts/reset/done/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete_new.html')),
    url(r'accounts/', include("django.contrib.auth.urls")),
    url(r'', include("memes.urls")),
]

memes/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.mem_list, name="mem_list"),
    url(r'^memchik/(?P<pk>\d+)/$', views.mem_detail, name="mem_detail"),
    url(r'^mem/new/$', views.mem_new, name="mem_new"),
    url(r'^mem/(?P<pk>\d+)/edit/$', views.mem_edit, name='mem_edit'),
    url(r'^drafts/$', views.mem_draft_list, name="mem_draft_list"),
    url(r'^mem/(?P<pk>\d+)/publish/$', views.mem_publish, name="mem_publish"),
    url(r'^mem/(?P<pk>\d+)/remove/$', views.mem_remove, name="mem_remove"),
    url(r'^mem/(?P<pk>\d+)/comment/$', views.add_comment_to_mem, name="add_comment_to_mem"),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name="comment_approve"),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name="comment_remove"),
    url(r'^register/$', views.register, name="register"),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    url(r'^memology/$', views.memology_list, name="memology_list"),
]


if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

star_ratings/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import Rate
from . import app_settings


urlpatterns = [
    url(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

star_ratings/models.py
from __future__ import division, unicode_literals
from decimal import Decimal

import swapper
from warnings import warn
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models import Avg, Count, Sum
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from model_utils.models import TimeStampedModel

from . import app_settings, get_star_ratings_rating_model_name, get_star_ratings_rating_model


def _clean_user(user):
    if not app_settings.STAR_RATINGS_ANONYMOUS:
        if not user:
            raise ValueError(_("User is mandatory. Enable 'STAR_RATINGS_ANONYMOUS' for anonymous ratings."))
        return user
    return None


class RatingManager(models.Manager):
    def for_instance(self, instance):
        if isinstance(instance, self.model):
            raise TypeError("Rating manager 'for_instance' expects model to be rated, not Rating model.")
        ct = ContentType.objects.get_for_model(instance)
        ratings, created = self.get_or_create(content_type=ct, object_id=instance.pk)
        return ratings

    def ratings_for_instance(self, instance):
        warn("RatingManager method 'ratings_for_instance' has been renamed to 'for_instance'. Please change uses of 'Rating.objects.ratings_for_instance' to 'Rating.objects.for_instance' in your code.", DeprecationWarning)
        return self.for_instance(instance)

    def rate(self, instance, score, user=None, ip=None):
        if isinstance(instance, self.model):
            raise TypeError("Rating manager 'rate' expects model to be rated, not Rating model.")
        ct = ContentType.objects.get_for_model(instance)

        user = _clean_user(user)
        existing_rating = UserRating.objects.for_instance_by_user(instance, user)

        if existing_rating:
            if not app_settings.STAR_RATINGS_RERATE:
                raise ValidationError(_('Already rated.'))
            existing_rating.score = score
            existing_rating.save()
            return existing_rating.rating
        else:
            rating, created = self.get_or_create(content_type=ct, object_id=instance.pk)
            return UserRating.objects.create(user=user, score=score, rating=rating, ip=ip).rating


@python_2_unicode_compatible
class AbstractBaseRating(models.Model):
    """
    Attaches Rating models and running counts to the model being rated via a generic relation.
    """
    count = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)
    average = models.DecimalField(max_digits=6, decimal_places=3, default=Decimal(0.0))

    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey()

    objects = RatingManager()

    class Meta:
        unique_together = ['content_type', 'object_id']
        abstract = True

    @property
    def percentage(self):
        return (self.average / app_settings.STAR_RATINGS_RANGE) * 100

    def to_dict(self):
        return {
            'count': self.count,
            'total': self.total,
            'average': self.average,
            'percentage': self.percentage,
        }

    def __str__(self):
        return '{}'.format(self.content_object)

    def calculate(self):
        """
        Recalculate the totals, and save.
        """
        aggregates = self.user_ratings.aggregate(total=Sum('score'), average=Avg('score'), count=Count('score'))
        self.count = aggregates.get('count') or 0
        self.total = aggregates.get('total') or 0
        self.average = aggregates.get('average') or 0.0
        self.save()


class Rating(AbstractBaseRating):
    class Meta(AbstractBaseRating.Meta):
        swappable = swapper.swappable_setting('star_ratings', 'Rating')


class UserRatingManager(models.Manager):
    def for_instance_by_user(self, instance, user=None):
        ct = ContentType.objects.get_for_model(instance)
        user = _clean_user(user)
        if user:
            return self.filter(rating__content_type=ct, rating__object_id=instance.pk, user=user).first()
        else:
            return None

    def has_rated(self, instance, user=None):
        if isinstance(instance, get_star_ratings_rating_model()):
            raise TypeError("UserRating manager 'has_rated' expects model to be rated, not UserRating model.")

        rating = self.for_instance_by_user(instance, user=user)
        return rating is not None

    def bulk_create(self, objs, batch_size=None):
        objs = super(UserRatingManager, self).bulk_create(objs, batch_size=batch_size)
        for rating in set(o.rating for o in objs):
            rating.calculate()
        return objs


@python_2_unicode_compatible
class UserRating(TimeStampedModel):
    """
    An individual rating of a user against a model.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(blank=True, null=True)
    score = models.PositiveSmallIntegerField()
    rating = models.ForeignKey(get_star_ratings_rating_model_name(), related_name='user_ratings', on_delete=models.CASCADE)

    objects = UserRatingManager()

    class Meta:
        unique_together = ['user', 'rating']

    def __str__(self):
        if not app_settings.STAR_RATINGS_ANONYMOUS:
            return '{} rating {} for {}'.format(self.user, self.score, self.rating.content_object)
        return '{} rating {} for {}'.format(self.ip, self.score, self.rating.content_object)

star_ratings/forms.py
from __future__ import absolute_import
from django import forms

from . import get_star_ratings_rating_model
from .models import UserRating


class CreateUserRatingForm(forms.ModelForm):
    class Meta:
        model = UserRating
        exclude = [
            'count',
            'total',
            'average',
            'rating',
        ]

    def __init__(self, obj=None, *args, **kwargs):
        self.obj = obj
        super(CreateUserRatingForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        return get_star_ratings_rating_model().objects.rate(
            self.obj,
            self.cleaned_data['score'],
            user=self.cleaned_data['user'],
            ip=self.cleaned_data['ip']
        )

star_ratings/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import View

from . import app_settings, get_star_ratings_rating_model
from .forms import CreateUserRatingForm
from .compat import is_authenticated
import json


class Rate(View):
    model = get_star_ratings_rating_model()

    def get_object(self):
        """
        Returns the model instance we're rating from the URL params.
        """
        content_type = ContentType.objects.get_for_id(self.kwargs.get('content_type_id'))
        return content_type.get_object_for_this_type(pk=self.kwargs.get('object_id'))

    def post(self, request, *args, **kwargs):
        def _post(request, *args, **kwargs):
            data = request.POST or json.loads(request.body.decode())

            return_url = data.pop('next', '/')
            if 'HTTP_X_REAL_IP' in self.request.META:
                data['ip'] = self.request.META['HTTP_X_REAL_IP']
            else:
                data['ip'] = self.request.META['REMOTE_ADDR']

            data['user'] = is_authenticated(request.user) and request.user.pk or None

            res_status = 200

            try:
                form = CreateUserRatingForm(data=data, obj=self.get_object())
                if form.is_valid():
                    rating = form.save()
                    result = rating.to_dict()
                    result['user_rating'] = int(form.cleaned_data['score'])
                else:
                    result = {'errors': form.errors}
                    res_status = 400
            except ValidationError as err:
                result = {'errors': err.message}
                res_status = 400

            if request.is_ajax():
                return JsonResponse(data=result, status=res_status)
            else:
                return HttpResponseRedirect(return_url)

        if not app_settings.STAR_RATINGS_ANONYMOUS:
            return login_required(_post)(request, *args, **kwargs)

        return _post(request, *args, **kwargs)

star_ratings/templates/star_ratings/widget.html
{% extends "star_ratings/widget_base.html" %}

star_ratings/templates/star_ratings/widget_base.html
{% load i18n %}
{% block rating_style %}
<style>
    #{{ id }} .star-ratings-rating-full, #{{ id }} .star-ratings-rating-empty {
        width: {{ icon_width }}px;
        height: {{ icon_height }}px;
        background: url({{ sprite_image }}) no-repeat;
        background-size: {{ sprite_width }}px;
    }

    #{{ id }} .star-ratings-rating-empty {
        background-position: -{{ icon_width }}px 0;
    }

    {% if user.is_authenticated and editable %}
    #{{ id }} .star-ratings-rating-full:hover, #{{ id }} .star-ratings-rating-empty:hover {
        background-position: -{{ icon_width|add:icon_width }}px 0;
    }
    {% endif %}
</style>
{% endblock rating_style %}

{% block rating_container %}
<div id="{{ id }}" class="star-ratings" data-max-rating="{{ star_count }}" data-avg-rating="{{ rating.average }}">
    {% block rating_stars %}
        <div class="star-ratings-rating-stars-container">
            <ul class="star-ratings-rating-background">
                {% for star in stars %}
                    <li>
                        {% if editable %}
                        <form action="{% url 'ratings:rate' rating.content_type_id rating.object_id %}" class="star-ratings-rate-action" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{ star }}" name="score">
                            <input type="hidden" value="{{ request.path }}" name="next">
                            <button type="submit" class="star-ratings-rating-empty" data-score="{{ star }}"></button>
                        </form>
                        {% elif user.is_authenticated %}
                            <span class="star-ratings-rating-empty"></span>
                        {% else %}
                            <span class="star-ratings-rating-empty" title="{% trans 'Log in to rate' as title_login %}{{ title_login|escape }}"></span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

            <ul class="star-ratings-rating-foreground" style="width: {{ percentage|floatformat }}%">
                {% for star in stars %}
                    <li>
                    {% if editable %}
                    <form action="{% url 'ratings:rate' rating.content_type_id rating.object_id %}" class="star-ratings-rate-action" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ star }}" name="score">
                        <input type="hidden" value="{{ request.path }}" name="next">
                        <button type="submit" class="star-ratings-rating-full" data-score="{{ star }}"></button>
                    </form>
                    {% else %}
                        <span class="star-ratings-rating-full" title="Log in to rate"></span>
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endblock %}
    <div class="rate">
        {% block rating_detail %}
        {% block rating_average %}
        <div class="star-ratings-rating-average">{% trans 'AVG: ' %} <span class='star-ratings-rating-value'>{{ rating.average|floatformat:"-2" }}</span></div>
        {% endblock rating_average %}
        {% block rating_count %}
        <div class="star-ratings-rating-count">{% trans 'Amount: ' %} <span class='star-ratings-rating-value'>{{ rating.count }}</span></div>
        {% endblock rating_count %}
        {% block rating_user %}
        {% if not user.is_authenticated and not anonymous_ratings and not read_only %}
            <div class="please_login">{% trans 'Please log in to rate.' %}</div>
        {% else %}
            <div class="star-ratings-rating-user">{% trans 'You Rated: ' %} <span class='star-ratings-rating-value'>{% if user_rating %}{{ user_rating.score }}{% else %}{% trans 'Not rated' %}{% endif %}</span></div>
        {% endif %}
        {% endblock rating_user %}
        <div class="star-ratings-errors"></div>
        {% endblock rating_detail %}
    </div>
</div>
{% endblock rating_container %}